print("Program starting.\n")
hex = input("Insert a hex color: ")
print()
print("Colors")
print(f"- Red {hex[1:3]}")
print(f"- Green {hex[3:5]}")
print(f"- Blue {hex[5:7]}")
print()
print("Program ending.")